spring:
  datasource:
    url: jdbc:mysql://localhost:3306/access_tracker?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&useUnicode=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.accesstracker.entity
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: NULL
    
server:
  port: 8080

# Custom configuration for thread pool
access-tracker:
  async:
    core-pool-size: 5
    max-pool-size: 10
    queue-capacity: 25
    thread-name-prefix: access-tracker-async-
